### PR TITLE
Implement Scaling

### PR DESCRIPTION
**Pull request by davidhalter**
Currently we have to recreate servers if we want to scale them.

This pull request fixes this.

### CODE REVIEW

**Comment by davidhalter** [comment]
@ferdinandhuebner Do you have time / do you want to QA this? If not I'll ask somebody internally with limited golang knowledge.

**Comment by ferdinandhuebner** [comment]
@davidhalter I can take a look later today

**Review by ferdinandhuebner — APPROVED** [review]
Looks good to me.

A somewhat related question: Some attributes on the server like `volume_size_gb` or `bulk_volume_size_gb` are currently defined with `ForceNew: true`. Is that really the case or can they be resized like the server itself?

**Comment by davidhalter** [comment]
Good point. Separate pull request will follow probably next week.


bulk_volume_size_gb will probably be ignored, because it's deprecated anyway (https://www.cloudscale.ch/en/api/v1#servers-create). People should just use the volumes endpoint instead. However for the root volume I agree that we should be able to scale it.

**Pull request merged**
