### PR TITLE
Migrating to the Terraform Plugin SDK.

### PR DESCRIPTION
**Pull request by lazzurs**
Migrating to the Terraform Plugin SDK using the automated migration
tool. Build works and no error with the migration tool.

### CODE REVIEW

**Comment by davidhalter** [comment]
I don't really know if this makes sense, so feel free to merge yourself.

**Comment by lazzurs** [comment]
I can't merge into this repo however would be happy to merge if I did. Terraform has moved away from having providers call Terraform directly into using a Plugin SDK and all this does is move this provider over to the new Plugin SDK repo.

https://www.hashicorp.com/blog/announcing-the-terraform-plugin-sdk/

**Comment by lazzurs** [comment]
@davidhalter anything more I can do to get this merged?

**Comment by davidhalter** [comment]
@lazzurs Is there a way you can remove all the vendor changes? I would like to run `go mod vendor` myself.

It's just that for security reasons I would consider this to be more secure. I have no idea how good go packaging protects me from you putting in something malicious.

**Comment by lazzurs** [comment]
@davidhalter No worries, I will push to this PR/branch shortly without all of the vendor changes.

**Comment by lazzurs** [comment]
Pushed now without vendor changes @davidhalter

**Comment by davidhalter** [comment]
@lazzurs Thanks a lot! I will keep this issue open for a while.

I will look at this again in the new year. Unfortunately we have other priorities in our company for now, but I will definitely get around to it.

This looks really good, so I suppose you don't have to do anything more. Consider this "done" from your side, it's just that now we have to act :)

**Comment by davidhalter** [comment]
Thanks again for doing this!

**Pull request merged**
